

export const GET_ITEMS = 'GET_ITEMS';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const GET_MOUSE = 'GET_MOUSE';
export const MOUSE_LOADING = 'MOUSE_LOADING';

export const GET_MOUSEPAD = 'GET_MOUSEPAD';
export const MOUSEPAD_LOADING = 'MOUSEPAD_LOADING';

export const GET_KEYBOARD = 'GET_KEYBOARD';
export const KEYBOARD_LOADING = 'KEYBOARD_LOADING';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';
